package bit.com.a.admin;

public class DateParam {
    private String TIMESTAMPDIFF0;
	private String TIMESTAMPDIFF1;
	private String TIMESTAMPDIFF2;
	private String TIMESTAMPDIFF3;
	private String TIMESTAMPDIFF4;
	private String TIMESTAMPDIFF5;
	private String TIMESTAMPDIFF6;
	
	public DateParam() {
	}

	public DateParam(String tIMESTAMPDIFF0, String tIMESTAMPDIFF1, String tIMESTAMPDIFF2, String tIMESTAMPDIFF3, String tIMESTAMPDIFF4, String tIMESTAMPDIFF5, String tIMESTAMPDIFF6) {
		TIMESTAMPDIFF0 = tIMESTAMPDIFF0;
		TIMESTAMPDIFF1 = tIMESTAMPDIFF1;
		TIMESTAMPDIFF2 = tIMESTAMPDIFF2;
		TIMESTAMPDIFF3 = tIMESTAMPDIFF3;
		TIMESTAMPDIFF4 = tIMESTAMPDIFF4;
		TIMESTAMPDIFF5 = tIMESTAMPDIFF5;
		TIMESTAMPDIFF6 = tIMESTAMPDIFF6;
	}

	public String getTIMESTAMPDIFF0() {
		return TIMESTAMPDIFF0;
	}

	public void setTIMESTAMPDIFF0(String tIMESTAMPDIFF0) {
		TIMESTAMPDIFF0 = tIMESTAMPDIFF0;
	}

	public String getTIMESTAMPDIFF1() {
		return TIMESTAMPDIFF1;
	}

	public void setTIMESTAMPDIFF1(String tIMESTAMPDIFF1) {
		TIMESTAMPDIFF1 = tIMESTAMPDIFF1;
	}

	public String getTIMESTAMPDIFF2() {
		return TIMESTAMPDIFF2;
	}

	public void setTIMESTAMPDIFF2(String tIMESTAMPDIFF2) {
		TIMESTAMPDIFF2 = tIMESTAMPDIFF2;
	}

	public String getTIMESTAMPDIFF3() {
		return TIMESTAMPDIFF3;
	}

	public void setTIMESTAMPDIFF3(String tIMESTAMPDIFF3) {
		TIMESTAMPDIFF3 = tIMESTAMPDIFF3;
	}

	public String getTIMESTAMPDIFF4() {
		return TIMESTAMPDIFF4;
	}

	public void setTIMESTAMPDIFF4(String tIMESTAMPDIFF4) {
		TIMESTAMPDIFF4 = tIMESTAMPDIFF4;
	}

	public String getTIMESTAMPDIFF5() {
		return TIMESTAMPDIFF5;
	}

	public void setTIMESTAMPDIFF5(String tIMESTAMPDIFF5) {
		TIMESTAMPDIFF5 = tIMESTAMPDIFF5;
	}

	public String getTIMESTAMPDIFF6() {
		return TIMESTAMPDIFF6;
	}

	public void setTIMESTAMPDIFF6(String tIMESTAMPDIFF6) {
		TIMESTAMPDIFF6 = tIMESTAMPDIFF6;
	}

	@Override
	public String toString() {
		return "DateParam [TIMESTAMPDIFF0=" + TIMESTAMPDIFF0 + ", TIMESTAMPDIFF1=" + TIMESTAMPDIFF1
				+ ", TIMESTAMPDIFF2=" + TIMESTAMPDIFF2 + ", TIMESTAMPDIFF3=" + TIMESTAMPDIFF3 + ", TIMESTAMPDIFF4="
				+ TIMESTAMPDIFF4 + ", TIMESTAMPDIFF5=" + TIMESTAMPDIFF5 + ", TIMESTAMPDIFF6=" + TIMESTAMPDIFF6 + "]";
	}
}